-- ══════════════════════════════════════════════════════════
-- LEXOS — MIGRATION 004
-- Adds source_loop tracking to staging table.
-- Adds processed_at to lexos_misses so the miss loop can
-- avoid re-processing already-handled misses.
-- ══════════════════════════════════════════════════════════

-- Source loop tag on staging entries
-- NULL = original generation pipeline
-- 'miss' = generated by miss loop
-- 'semantic_promote' = generated by semantic promote loop
ALTER TABLE lexos_entries_staging
  ADD COLUMN IF NOT EXISTS source_loop VARCHAR(50)
  CHECK (source_loop IN ('miss', 'semantic_promote'));

-- Mark when a miss was picked up by the loop so it isn't reprocessed
ALTER TABLE lexos_misses
  ADD COLUMN IF NOT EXISTS processed_at TIMESTAMP;

-- Index to speed up the loop query (unprocessed high-frequency misses first)
CREATE INDEX IF NOT EXISTS idx_misses_loop
  ON lexos_misses (frequency DESC, lang, domain)
  WHERE processed_at IS NULL;
