import { getDb } from '../client';

// ──────────────────────────────────────────────────────────
// Enrich queries — exact match + call logging
// ──────────────────────────────────────────────────────────

export interface ExactMatchResult {
  intent:       string;
  confidence:   number;
  matched_head: string;
  variant_type: string;
}

export interface LogEnrichCallInput {
  call_id:        string;
  input_phrase:   string;
  matched_intent: string | null;
  match_type:     'exact' | 'semantic' | 'miss';
  latency_ms:     number;
  product_id?:    string;
  tenant_id?:     string;
  user_id?:       string;
  workflow?:      string;
  lang:           string | null;
}

export interface EnrichedContext {
  intent:   string;
  variants: string[];
  tier:     string | null;
  domain:   string;
}

export interface EnrichCallRow {
  call_id:        string;
  input_phrase:   string;
  matched_intent: string | null;
  match_type:     string | null;
  lang:           string | null;
  product_id:     string | null;
  tenant_id:      string | null;
  workflow:       string | null;
}

// ── Internal row shape returned from the nested Supabase select ──

interface TermVariantRow {
  variant_type: string;
  value:        string;
  confidence:   number | null;
  lexos_terms: {
    intent_id:    string;
    language_code: string;
    domain:       string;
    tenant_id:    string | null;
    active:       boolean;
    valid_from:   string;
    valid_until:  string | null;
    lexos_intents: {
      intent_name: string;
    };
  };
}

/** Strip trailing punctuation + whitespace (handles Devanagari danda ।, ASCII . ! ? , etc.) */
function normPhrase(s: string): string {
  return s.replace(/[।॥।\.!?,\s]+$/, '').trim();
}

/**
 * Exact case-insensitive match against COLLOQUIAL and CODE_MIXED variants.
 *
 * Fetches all rows matching the phrase (across all tenants/languages),
 * then filters in JS to apply:
 *   - language + domain gate
 *   - bi-temporal validity
 *   - tenant layering: tenant-specific > global
 *
 * Returns the best match or null if none found.
 */
export async function exactMatch(
  phrase:   string,
  lang:     string | null,   // null = search across all languages
  domain:   string,
  tenantId?: string,
): Promise<ExactMatchResult | null> {
  const db = getDb();
  const now = new Date();
  const normalized = normPhrase(phrase);

  const { data, error } = await db
    .from('term_variants')
    .select(`
      variant_type,
      value,
      confidence,
      lexos_terms!inner (
        intent_id,
        language_code,
        domain,
        tenant_id,
        active,
        valid_from,
        valid_until,
        lexos_intents!inner (
          intent_name
        )
      )
    `)
    .ilike('value', normalized)
    .in('variant_type', ['COLLOQUIAL', 'CODE_MIXED']);

  if (error) throw new Error(`exactMatch query: ${error.message}`);
  if (!data || data.length === 0) return null;

  // Filter: language (skipped when null), domain, active, bi-temporal validity
  const candidates = (data as unknown as TermVariantRow[]).filter(row => {
    const t = row.lexos_terms;
    if (!t || !t.active) return false;
    if (lang !== null && t.language_code !== lang) return false;
    if (t.domain !== domain) return false;
    const from   = new Date(t.valid_from);
    const until  = t.valid_until ? new Date(t.valid_until) : null;
    if (from > now) return false;
    if (until && until < now) return false;
    return true;
  });

  if (candidates.length === 0) return null;

  // Tenant layering: prefer tenant-specific hit, fall back to global
  const best =
    (tenantId ? candidates.find(c => c.lexos_terms.tenant_id === tenantId) : null) ??
    candidates.find(c => c.lexos_terms.tenant_id === null) ??
    candidates[0];

  return {
    intent:       best.lexos_terms.lexos_intents.intent_name,
    confidence:   typeof best.confidence === 'number' ? best.confidence : 0.9,
    matched_head: best.value,
    variant_type: best.variant_type,
  };
}

/**
 * Logs an enrich call to lexos_enrich_calls.
 * call_id is generated by the caller (crypto.randomUUID) so it can be
 * returned in the response without awaiting this insert.
 */
export async function logEnrichCall(input: LogEnrichCallInput): Promise<void> {
  try {
    const db = getDb();
    await db.from('lexos_enrich_calls').insert({
      call_id:        input.call_id,
      input_phrase:   input.input_phrase,
      matched_intent: input.matched_intent,
      match_type:     input.match_type,
      latency_ms:     input.latency_ms,
      product_id:     input.product_id  ?? null,
      tenant_id:      input.tenant_id   ?? null,
      user_id:        input.user_id     ?? null,
      workflow:       input.workflow    ?? null,
      lang:           input.lang,
    });
  } catch (err) {
    console.warn('logEnrichCall failed (non-fatal):', (err as Error).message);
  }
}

/**
 * Fetches a single enrich call row by call_id.
 * Used by the outcome PATCH handler to retrieve phrase details for the miss loop.
 */
export async function getEnrichCallById(callId: string): Promise<EnrichCallRow | null> {
  const db = getDb();
  const { data, error } = await db
    .from('lexos_enrich_calls')
    .select('call_id, input_phrase, matched_intent, match_type, lang, product_id, tenant_id, workflow')
    .eq('call_id', callId)
    .maybeSingle();
  if (error) throw new Error(`getEnrichCallById: ${error.message}`);
  return (data as EnrichCallRow | null);
}

/**
 * Sets downstream_outcome on a logged enrich call.
 */
export async function updateEnrichOutcome(
  callId:  string,
  outcome: 'correct' | 'incorrect' | 'abandoned',
): Promise<void> {
  const db = getDb();
  const { error } = await db
    .from('lexos_enrich_calls')
    .update({ downstream_outcome: outcome })
    .eq('call_id', callId);
  if (error) throw new Error(`updateEnrichOutcome: ${error.message}`);
}

/**
 * Returns the top COLLOQUIAL/CODE_MIXED variants for a resolved intent + language.
 * Injected into the enrich response as enriched_context for the calling LLM.
 */
export async function getEnrichedContext(
  intentName: string,
  lang:       string,
  domain:     string,
): Promise<EnrichedContext | null> {
  const db = getDb();

  // Step 1 — intent_id
  const { data: intentRow, error: intentErr } = await db
    .from('lexos_intents')
    .select('intent_id')
    .eq('intent_name', intentName)
    .maybeSingle();
  if (intentErr || !intentRow) return null;

  // Step 2 — active term for this intent × language
  const { data: termRow, error: termErr } = await db
    .from('lexos_terms')
    .select('term_id, tier')
    .eq('intent_id', (intentRow as { intent_id: string }).intent_id)
    .eq('language_code', lang)
    .eq('domain', domain)
    .eq('active', true)
    .maybeSingle();
  if (termErr || !termRow) return null;
  const { term_id, tier } = termRow as { term_id: string; tier: string | null };

  // Step 3 — top variants
  const { data: varRows, error: varErr } = await db
    .from('term_variants')
    .select('value, variant_type')
    .eq('term_id', term_id)
    .in('variant_type', ['COLLOQUIAL', 'CODE_MIXED'])
    .limit(6);
  if (varErr || !varRows) return null;

  return {
    intent:   intentName,
    variants: (varRows as { value: string }[]).map(r => r.value),
    tier,
    domain,
  };
}
